In [1]:
import tensorflow as tf
import numpy as np

In [2]:
inputs = np.ones([10, 4, 1]).astype(np.float32)
print(inputs)
inputs = tf.convert_to_tensor(inputs, dtype=tf.float32)

inputs

[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]


<tf.Tensor: shape=(10, 4, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [3]:
states = np.ones([10, 4, 4]).astype(np.float32) * 1.5
print(states)
states = tf.convert_to_tensor(states, dtype=tf.float32)
states

[[[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5]]]


<tf.Tensor: shape=(10, 4, 4), dtype=float32, numpy=
array([[[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5]],

       [[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5]],

       [[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5]],

       [[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5]],

       [[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5]],

       [[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5]],

       [[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5]],

       [[1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
        [1.5, 1.5, 1.5, 1.5],
    

In [4]:
rnn_cell = tf.keras.layers.SimpleRNNCell(4)

In [5]:
rnn_cell(inputs = inputs, states = states)

(<tf.Tensor: shape=(10, 4, 4), dtype=float32, numpy=
 array([[[0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954]],
 
        [[0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954]],
 
        [[0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954]],
 
        [[0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091954],
         [0.9958691 , 0.58725405, 0.99540806, 0.92091